### ISSUE TITLE
Exceptions getting logged before the plugin is configured

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/theme-manager-plugin#14]
Exceptions like the following are being logged before a user configures their theme:

```
2020-06-22 19:29:23.227+0000 [id=11]	WARNING	h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: it.getHeaderHtml() in /user/admin/configure. Reason: java.lang.NullPointerException
java.lang.NullPointerException
	at io.jenkins.plugins.thememanager.ThemeUserProperty.forCurrentUser(ThemeUserProperty.java:39)
	at io.jenkins.plugins.thememanager.ThemeManagerPageDecorator.getHeaderHtml(ThemeManagerPageDecorator.java:63)
```

This may occur for every new user. NPE when `property == null`:

https://github.com/jenkinsci/theme-manager-plugin/blob/39d2dd9a09a64006a43f2286cf5d62f78d67c8e3/src/main/java/io/jenkins/plugins/thememanager/ThemeUserProperty.java#L39

**Comment by timja** [comment]
shouldn't that be annotated `CheckForNull` in core?

**Comment by daniel-beck** [comment]
Probably, those annotations are pretty recent in core.
